version: "2"

services:

    api-rest-database: 
        container_name: api-rest-database
        image: mysql:5.6
        environment:
            - MYSQL_ROOT_PASSWORD=betha123
            - MYSQL_DATABASE=userdb
        volumes:
            - data:/var/lib/mysql
        network_mode: "host"
        
    api-rest-spring:
        container_name: api-rest-spring  
        image: spring
        build:
            context: ./api-rest
            dockerfile: Dockerfile
        volumes:
            - /data/springboot
        depends_on: 
            - api-rest-database
        network_mode: "host"

    api-rest-angular:
        container_name: api-rest-angular
        image: angular
        build:
            context: ./frontend
            dockerfile: ./Dockerfile
        volumes:
            - /data/angular
        depends_on: 
            - api-rest-spring
        ports:
            - "4200:4200"
        network_mode: "host"

volumes:
    data:
